### ISSUE TITLE
ERROR Failed to read file: ".tmp/extracted/avb_pkmd.bin"

### ISSUE THREAD

**Issue by 0cwa** [pixincreate/PixeneOS#3]
On Fedora, not sure I put my keys in the right place, probably not relevant to this error though?

Building bramble stable.

```
10.384s  INFO Successfully extracted OTA
 10.384s  INFO Verifying partition hashes
 11.584s  INFO Checking ramdisk's otacerts.zip
 11.729s  INFO Verifying AVB signatures
 11.926s ERROR Failed to read file: ".tmp/extracted/avb_pkmd.bin"

Caused by:
    No such file or directory (os error 2)
Traceback (most recent call last):
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1009, in <module>
    main()
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1000, in main
    run(args, Path(temp_dir))
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 882, in run
    verify_ota(args.input, args.verify_public_key_avb, args.verify_cert_ota)
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 40, in verify_ota
    subprocess.check_call([
  File "/usr/lib64/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['avbroot', 'ota', 'verify', '--input', PosixPath('.tmp/bramble-ota_update-2024080600.zip'), '--public-key-avb', PosixPath('.tmp/extracted/avb_pkmd.bin'), '--cert-ota', PosixPath('.tmp/extracted/ota/META-INF/com/android/otacert')]' returned non-zero exit status 1.
Cleaning up...
Cleanup complete.
Cleaning up...
Cleanup complete.
```

**Comment by 0cwa** [comment]
Ah, ok, basically '--public-key-avb', PosixPath('.tmp/extracted/avb_pkmd.bin'), should be looking in .tmp/extracted/extracts/avb_pkmd.bin.  Not sure the best way to patch that but I might symlink to make it work for now.
