### ISSUE TITLE
No MSD Signature

### ISSUE THREAD

**Issue by 0cwa** [pixincreate/PixeneOS#6]
```
[*] Adding Custota seapp context: /tmp/tmps_a9i0br/system/fs_tree/system/etc/selinux/plat_seapp_contexts
[*] Verifying SSH signature: .tmp/modules/msd.zip
Couldn't read signature file: No such file or directory
Could not verify signature.
Traceback (most recent call last):
  File "/home/x/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1009, in <module>
    main()
  File "/home/x/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1000, in main
    run(args, Path(temp_dir))
  File "/home/x/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 927, in run
    inject_msd(
  File "/home/x/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 486, in inject_msd
    verify_ssh_sig(module_zip, module_sig, SSH_PUBLIC_KEY_CHENXIAOLONG)
  File "/home/x/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 402, in verify_ssh_sig
    subprocess.check_call([
  File "/usr/lib64/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh-keygen', '-Y', 'verify', '-f', '/tmp/tmp8si8jr_u', '-I', 'trusted', '-n', 'file', '-s', PosixPath('.tmp/modules/msd.zip.sig')]' returned non-zero exit status 255.
Cleanup is disabled. Exiting...
```
Contents of signatures and modules:
```
➜  PixeneOS git:(main) ✗ ls .tmp/signatures 
avbroot.zip.sig  custota-tool.zip.sig  custota.zip.sig
➜  PixeneOS git:(main) ✗ ls .tmp/modules   
alterinstaller.zip  bcr.zip  custota.zip  msd.zip  oemunlockonboot.zip
```
I don't know if the other modules will also require signatures...

(Fedora 40 x86)

**Comment by pixincreate** [comment]
> https://github.com/chenxiaolong/my-avbroot-setup/issues/3#issuecomment-2295296324

Are you still facing this error? I believe I need to add support to download signatures explicitly and pass them independently just like I've done for `custota` if the issue still persist.

**Comment by 0cwa** [comment]
Yes, I ran a pull and tried afresh the latest version.

**Comment by pixincreate** [comment]
I believe [this](https://github.com/pixincreate/PixeneOS/commit/c17ec18162086edd6eac4970fc489915433a02bb) should this.

**Comment by 0cwa** [comment]
It does!
