### ISSUE TITLE
Error while Patching Image: "Unsupported VABC compression: gz"

### ISSUE THREAD

**Issue by 0cwa** [pixincreate/PixeneOS#7]
I have gzip installed, I don't know what VABC is, couldn't find anything in the repos

```
  2.877s  INFO Compressing full image: vendor
  2.877s  INFO Needs updated CoW size estimate: vendor
  2.954s ERROR Failed to patch OTA zip

Caused by:
    0: Failed to patch payload: payload.bin
    1: Failed to compress image: vendor
    2: Unsupported VABC compression: gz
Traceback (most recent call last):
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1009, in <module>
    main()
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 1000, in main
    run(args, Path(temp_dir))
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 973, in run
    patch_ota(
  File "/home/user/PixeneOS/.tmp/my-avbroot-setup/patch.py", line 89, in patch_ota
    subprocess.check_call(cmd)
  File "/usr/lib64/python3.12/subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['avbroot', 'ota', 'patch', '--input', PosixPath('.tmp/bramble-ota_update-2024080600.zip'), '--output', PosixPath('.tmp/bramble-ota_update-2024080600.patched-dirty.zip'), '--key-avb', PosixPath('avb.key'), '--key-ota', PosixPath('ota.key'), '--cert-ota', PosixPath('ota.crt'), '--rootless', '--replace', 'system', PosixPath('/tmp/tmpyak332u5/images/system.img'), '--replace', 'vendor', PosixPath('/tmp/tmpyak332u5/images/vendor.img'), '--replace', 'vendor_boot', PosixPath('/tmp/tmpyak332u5/images/vendor_boot.img')]' returned non-zero exit status 1.
```
Home stretch!

**Comment by pixincreate** [comment]
This does not have anything to do with `PixeneOS`. Specific to [`my-avbroot-setup`](https://github.com/chenxiaolong/my-avbroot-setup) from what I can see.
