### ISSUE TITLE
[BUG] [fetcher] downloads ocassionally fail

### ISSUE THREAD

**Issue by 0cwa** [pixincreate/PixeneOS#9]
Fresh working directory, and fresh source.  It works if I add afsr to my path, same with avbroot and same thing with custota-tool.

All the binaries are in .tmp/tools/[name of binary]/[binary]

Fedora 40 x64

```
[*] Unpacking filesystem: /tmp/tmp96s37blm/system/raw.img
Traceback (most recent call last):
  File "/home/x/PixeneOS/.tmp/tools/my-avbroot-setup/patch.py", line 1009, in <module>
    main()
  File "/home/x/PixeneOS/.tmp/tools/my-avbroot-setup/patch.py", line 1000, in main
    run(args, Path(temp_dir))
  File "/home/x/PixeneOS/.tmp/tools/my-avbroot-setup/patch.py", line 890, in run
    unpack_fs(system_raw, system_dir)
  File "/home/x/PixeneOS/.tmp/tools/my-avbroot-setup/patch.py", line 161, in unpack_fs
    subprocess.check_call([
  File "/usr/lib64/python3.12/subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib64/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'afsr'
```

**Comment by pixincreate** [comment]
Please share download logs which is above in the beginning.

I would suggest you to try downloading again as I myself found some intermittent issues while the download happens that results some modules fail to download.

**Comment by pixincreate** [comment]
Did downloading again solved the issue?

**Comment by pixincreate** [comment]
# Possible implementation

Add retries to download the file again if it failed previously.

**Comment by 0cwa** [comment]
Yes it did
